version: '3.5'

services:
  nodejs:
    build: .docker/build/node
    container_name: nodejs
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default

  nginx:
    build: .docker/build/nginx
    container_name: nginx
    depends_on:
      - nodejs
    ports:
      - 8080:80
    networks:
      - default

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    volumes: 
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=codeeducation
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123456
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8081:80

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
